### ISSUE TITLE
FEMdoc.pdf characters not copy/paste ready for octave interpreter

### ISSUE THREAD

**Issue by NRJank** [AndreasStahel/FEMoctave#11]
documentation is set up well for copy/paste of example code snippets, but the font rendering appears to insert/use characters that create syntax errors.  E.g., the p.21 example:

```
LaplaceRectangle.m
FEMmesh = CreateMeshRect([0:0.1:1],[0:0.1:2],-1,-2,-1,-2);
%%FEMmesh = MeshUpgrade(FEMmesh,’quadratic’); %% uncomment to use quadratic elements
%%FEMmesh = MeshUpgrade(FEMmesh,’cubic’); %% uncomment to use cubic elements
u = BVP2Dsym(FEMmesh,1,0,0.25,0,0,0);
figure(1); FEMtrimesh(FEMmesh,u); xlabel(’x’); ylabel(’y’);
```

the xlabel and ylabel commands produce syntax errors because they're using ` instead of '.

Likely a conversion issue, but ideally they would render in copy/pastable text

**Comment by AndreasStahel** [comment]
Thank you for the positive response. In the meantime I found a way make copy&paste of code possible.
The next release 2.1.4 will use the new feature. 
If you want it now, grab doc/FEMdoc.pdf from the gitub site.

**Comment by AndreasStahel** [comment]
Improved for the next release
