### ISSUE TITLE
Unable to install in Octave 7 via web

### ISSUE THREAD

**Issue by gonzavelasco99** [AndreasStahel/FEMoctave#2]
>> pkg install "https://github.com/AndreasStahel/FEMoctave/archive/v2.0.3.tar.gz"
warning: load_path: C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1: No such file or director
y
warning: load-path: update failed for 'C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1', remo
ving from path
warning: load_path: C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1: No such file or director
y
warning: called from
    unpack at line 273 column 5
    untar at line 48 column 5
    install at line 99 column 9
    pkg at line 603 column 9

warning: load-path: update failed for 'C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1', remo
ving from path
warning: called from
    unpack at line 273 column 5
    untar at line 48 column 5
    install at line 99 column 9
    pkg at line 603 column 9

warning: load_path: C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1: No such file or director
y
warning: called from
    unpack at line 276 column 5
    untar at line 48 column 5
    install at line 99 column 9
    pkg at line 603 column 9

warning: load-path: update failed for 'C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1', remo
ving from path
warning: called from
    unpack at line 276 column 5
    untar at line 48 column 5
    install at line 99 column 9
    pkg at line 603 column 9

error: parse error near line 60 of file C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave-2.0.1\MeshU
pgrade.m

  nNodes: invalid use of symbol as both variable and command

>>>       nNodes +=1;
         ^
error: called from
    doc_cache_create>create_cache at line 116 column 20
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 16
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9
>>

**Comment by AndreasStahel** [comment]
This is a conflict introduced by the newest version 7.1 of Octave.
The new related 2.0.4 of FEMoctave should install just fine

**Comment by gonzavelasco99** [comment]
The problem persists as shown below:

_error: parse error near line 60 of file C:\Users\gonza\AppData\Roaming\octave\api-v57\packages\femoctave
-2.0.1\MeshUpgrade.m

  nNodes: invalid use of symbol as both variable and command

>>>       nNodes +=1;
         ^
error: called from
    doc_cache_create>create_cache at line 116 column 20
    gen_doc_cache_in_dir>@<anonymous> at line 150 column 16
    doc_cache_create>gen_doc_cache_in_dir at line 151 column 9
    doc_cache_create at line 62 column 12
    install>generate_lookfor_cache at line 840 column 5
    install at line 241 column 7
    pkg at line 603 column 9_
